workflows:
  ios-flet-workflow:
    name: Compilar Garaje iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        FLET_PLATFORM: ipa
    scripts:
      - name: Instalar Flet y dependencias
        script: |
          pip install -r requirements.txt
      - name: Compilar aplicacion IPA
        script: |
          flet build ipa
    artifacts:
      - build/ipa/*.ipa
